sudo: true

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  # Install Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Set up an environment for Python
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # Install mpi4py with mpich
  - conda install -n test-environment -q numpy scipy pip
  - conda install -n test-environment -q --channel mpi4py mpich mpi4py

  # Install py-earth, matlab_wrapper
  - pip install --upgrade pip
  - pip install six http://github.com/scikit-learn-contrib/py-earth/tarball/master
  - pip install matlab_wrapper

  # Install subprocess32 if Python2 is being used
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install subprocess32;
    fi

  # Install pySOT
  - python setup.py install

script:
  - cd ./pySOT/test/
  - make all
  - make test
  - make testmpi
