sudo: true

language: python

matrix:
  include:
    - os: linux
      python: 2.7
      sudo: required

    - os: osx
      language: generic
      sudo: required

install:

  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q numpy scipy matplotlib pip
  - conda install -q --channel mpi4py mpich mpi4py

script:
  - pip install --upgrade pip
  - pip install inspyred
  - python setup.py install
  - cd ./pySOT/test/
  - make all
  - make test